### ISSUE TITLE
钱晨曦的问题

### ISSUE THREAD

**Issue by wudan3** [wov/Maps#155]
1.  抵用券的字数限制我觉得可以放宽一些
比如说满1000减100 这样的抵用券信息就被限制了 因为字数超出了-----改成字数限制为10
2. Tab的字数限制改动
3. 品牌团的logo显示问题
4. 商品轮播最好做成可以自己轮播的

**Comment by wudan3** [comment]
5. 目前头图尺寸太大，而且不能自己调大小，最好设置成1242px * 373px

**Comment by zhiqingz** [comment]
头图尺寸没有限制限制，只是推荐值。

**Comment by zhiqingz** [comment]
4放到下期做。前面3个都改了

**Comment by wudan3** [comment]
3. 品牌团logo红米手机前端显示还有问题。后台编辑跟预览还是之前的

**Comment by wudan3** [comment]
品牌团字体改改，感觉太空了
![default](https://cloud.githubusercontent.com/assets/12813257/8126827/82534514-1124-11e5-8a3b-e82fb62853fa.png)

**Comment by wudan3** [comment]
前3个都验证通过
