### ISSUE TITLE
标题，添加模块类型为抢购用，设置开始/结束时间保存，展示控制框不会立即显示设置时间，需要强制刷新页面才能显示正常

### ISSUE THREAD

**Issue by xieshihu** [wov/Maps#50]
测试步骤：
1.进入maps编辑页面；
2.添加模块类型为抢购用，设置开始/结束时间保存；
测试结果：展示控制框不会立即显示设置时间，需要强制刷新页面显示正常。

**Comment by zhiqingz** [comment]
@wov 
title3 的startTicking这个方法里 beginTimeStamp
