### ISSUE TITLE
【通用配置模块底图】 根据不同的模块展示栏，调整模块底图尺寸和大小

### ISSUE THREAD

**Issue by xieshihu** [wov/Maps#60]
1.TAB，添加模块类型，通用配置，配置模块底图，图片尺寸为1024*768 大小为453，点击浏览无任何提示，展示控制框不显示设置图片效果，保存预览也不显示设置图片效果。

2.标题，添加模块类型，通用配置，配置模块底图，点击浏览，展示控制框显示设置图片只显示一部分，保存预览设置图片也只显示一部分。

3.活动规则，添加模块类型，通用配置，配置模块底图，点击浏览，展示控制框显示设置图片只显示一部分，保存预览设置图片也只显示一部分。

4.优惠券，添加模块类型，通用配置，配置模块底图，点击浏览，展示控制框显示设置图片只显示一部分，保存预览设置图片也只显示一部分。

5.轮播图，添加模块类型，通用配置，配置模块底图，图片尺寸为1024*768 大小为453，点击浏览无任何提示，展示控制框不显示设置图片效果，保存预览也不显示设置图片效果。

6.会场入口，添加模块类型，通用配置，配置模块底图，点击浏览，展示控制框显示设置图片只显示一部分，保存预览设置图片也只显示一部分。

7.商品展示，添加模块类型轮播，通用配置，配置模块底图，点击浏览，展示控制框显示设置图片只显示一部分，保存预览设置图片也只显示一部分。

8.头图，添加模块类型，通用配置，配置模块底图，图片尺寸为1024*768 大小为453，点击浏览无任何提示，展示控制框不显示设置图片效果，保存预览也不显示设置图片效果。

**Comment by kevin14** [comment]
这些地图都设置成功了 只不过被前面的图片覆盖了

**Comment by zhiqingz** [comment]
解决方案，取消模块背景图设置
