### ISSUE TITLE
【会场导航】添加模块类型为会场导航，在模块配置栏设置模块底图，保存预览，模块底图不显示

### ISSUE THREAD

**Issue by xieshihu** [wov/Maps#70]
操作步骤：
1.添加模块类型为会场导航图文，
2.在模块配置栏中设置模块底图，保存预览
测试结果：设置模块底图保存预览不显示。
![default](https://cloud.githubusercontent.com/assets/12635659/7907955/5b7ea3d0-0872-11e5-9622-aef6348f625d.jpg)
![3](https://cloud.githubusercontent.com/assets/12635659/7907967/8334c710-0872-11e5-9737-7c73ce6a7e46.png)

**Comment by kevin14** [comment]
这个模块不支持底图配置的，即使配置了 也将会被覆盖掉

**Comment by kevin14** [comment]
解决方案：不给用户这个配置选项
