### ISSUE TITLE
【模块类型】进入maps编辑页面，配置多个模块类型，保存预览模块类型与模块类型之间间隙太大

### ISSUE THREAD

**Issue by xieshihu** [wov/Maps#79]
操作步骤：
1.进入maps编辑页面，配置多个模块类型保存预览显示效果

测试结果：模块类型之间间隙太大，影响体验
![default](https://cloud.githubusercontent.com/assets/12635659/7931634/d0522420-0944-11e5-95b4-e3efd12906bf.png)

**Comment by zhiqingz** [comment]
这个在手机上不会太大，按设计规范来的。
