### ISSUE TITLE
【优惠券】进入maps编辑页面，点击优惠券添加模块类型，保存预览，展示控制框与预览页面显示不一致。

### ISSUE THREAD

**Issue by xieshihu** [wov/Maps#85]
操作步骤：
1.进入maps编辑页面，点击优惠券添加模块类型；
2.点保存预览，查看展示控制框与预览页面显示

测试结果：预览页面与展示控制框显示不一致
![default](https://cloud.githubusercontent.com/assets/12635659/7954310/fe0ca6d0-0a00-11e5-927d-80768d556d5b.jpg)

**Comment by zhiqingz** [comment]
这个是因为编辑页空间有限 无法展示全。不算是bug
