### ISSUE TITLE
【手机访问】通过手机扫面二维码，点击会场导航，不会跳转到会场链接地址网页

### ISSUE THREAD

**Issue by xieshihu** [wov/Maps#91]
操作步骤：
1.进入maps编辑页面，点击会场导航，添加图文；
2.在模块配置栏，配置会场链接，保存预览

测试结果：配置会场链接，保存预览点击会场导航，不会跳转到会场链接地址网页

                通过手机扫描，点击会场导航，也不会跳转到会场链接地址网页

http://m.yhd.com:8090/tsmm/maps/edit.html?map_uat=MAPS_TOKEN926687511433385774371&pageId=111

**Comment by kevin14** [comment]
a标签的链接请用双引号包起来 @zhiqingz
