### ISSUE TITLE
【商品展示】进入maps编辑页面，添加图文一行二/一行一，在模块配置栏设置商品显示数目，不能添加商品显示数量

### ISSUE THREAD

**Issue by xieshihu** [wov/Maps#98]
操作步骤：

1.进入maps编辑页面，点击商品展示添加图文一行二/一行一；

2.在模块配置栏设置商品显示数量，开始设置小于默认的数量保存；

3.再次设置商品显示数量为默认数量保存

测试结果：再次设置为默认数量展示控制不会显示出默认商品数量，即商品数量不能做增加操作。

**Comment by zhiqingz** [comment]
可能是因为设置的数量大于商品的总量
